#! /bin/sh

#
#	AUTOSTART
#
picom --config $HOME/.config/picom/picom.conf &
feh --bg-scale $HOME/Pictures/Wallpapers/cyberpunk.jpg &
polybar -c $HOME/.config/polybar/cyberpunk main &
pgrep -x sxhkd > /dev/null || sxhkd &

#
#	BSPWM CONFIG
#
bspc monitor -d          

bspc config border_width         2
bspc config window_gap          12

bspc config normal_border_color 	'#000000'
bspc config active_border_color 	'#aa0000'
bspc config focused_border_color	'#0090ff'

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Firefox desktop='^2'
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

